### ISSUE TITLE
low mAP, I can't figure out what went wrong

### ISSUE THREAD

**Issue by zhanjw** [sheepover96/deep_cross_modal_hash#3]
Hello, I would like to ask if you can reproduce the result of the paper?
After 50 epoch training using your code and flicker25k datasets, my query mAP of cross-modal is only about 4.5%, and the training mAP only get 7%. I don't know what went wrong.  It seems like completely impossible to fit. Can you help me?

**Comment by sheepover96** [comment]
I'm sorry, in this implementation, some points are differs from original implementation such as method of batch making, architecture and number of units, pre-training of CNN and so on. And I did not test my implementation on flicker-25k because I couldn't get experiments data from Baidu web site.
If you want to reproduce the result, I think referencing https://github.com/WendellGul/DCMH is better.
Thank you for asking!

**Comment by zhanjw** [comment]
thanks for your assisstance anyway, i'll try.
